name: journal_project
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  avatar_glow: ^1.1.0
  flutter_auth_buttons: ^0.6.0
  google_sign_in: ^4.0.4
  intl: ^0.16.1
  table_calendar: ^2.2.2
  shared_preferences: ^0.5.6+1
  provider: ^4.0.4
  flare_flutter: ^2.0.1

  #firebase
  firebase_core: ^0.4.4+2
  cloud_firestore: ^0.13.4
  firebase_auth: ^0.14.0+5

  #widget
  flutter_rounded_date_picker: ^1.0.3
  fluttertoast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/images/
